CREATE DATABASE IF NOT EXISTS jobtrack CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE jobtrack;
CREATE TABLE IF NOT EXISTS users(id INT AUTO_INCREMENT PRIMARY KEY,name VARCHAR(120) NOT NULL,email VARCHAR(180) NOT NULL UNIQUE,password_hash VARCHAR(255) NOT NULL);
CREATE TABLE IF NOT EXISTS applications(id INT AUTO_INCREMENT PRIMARY KEY,user_id INT NOT NULL,company VARCHAR(150) NOT NULL,position VARCHAR(180) NOT NULL,type VARCHAR(50) NOT NULL,location VARCHAR(150) NULL,status VARCHAR(50) NOT NULL DEFAULT 'Applied',priority VARCHAR(20) NOT NULL DEFAULT 'Medium',applied_date DATETIME NOT NULL,interview_date DATETIME NULL,notes TEXT NULL,CONSTRAINT fk_app_user FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE);
